import assert from "node:assert/strict";
import { spawnSync } from "node:child_process";
import { cp, mkdir, mkdtemp, rm, writeFile } from "node:fs/promises";
import { tmpdir } from "node:os";
import { join } from "node:path";
import { pathToFileURL } from "node:url";
import test from "node:test";

const REPO_ROOT = join(import.meta.dirname, "..");
const CLI = join(REPO_ROOT, "dist/src/index.js");
const FIXTURE = join(import.meta.dirname, "fixtures", "local-workspace");
const FETCH_THROW = pathToFileURL(
  join(import.meta.dirname, "fixtures", "preload-fetch-throw.mjs"),
).href;

// Run the built CLI. By default a fetch-throwing preload is injected so any
// network access fails loudly; pass preload:false to allow real fetch.
const runCli = (args, { cwd, preload = true } = {}) => {
  const nodeArgs = preload ? ["--import", FETCH_THROW, CLI, ...args] : [CLI, ...args];
  return spawnSync(process.execPath, nodeArgs, {
    cwd: cwd ?? REPO_ROOT,
    encoding: "utf8",
  });
};

const withCwd = async (fn) => {
  const dir = await mkdtemp(join(tmpdir(), "wmts-cli-"));
  try {
    return await fn(dir);
  } finally {
    await rm(dir, { force: true, recursive: true });
  }
};

test("complete local fixture generates to stdout with no network", async () => {
  await withCwd(async (cwd) => {
    const result = runCli(["--from-folder", FIXTURE, "-"], { cwd });
    assert.equal(result.status, 0, result.stderr);
    assert.match(
      result.stdout,
      /^\/\/ This file is auto-generated by windmill-ts/,
    );
    // stdout is only generated code; no diagnostics leaked into it.
    assert.equal(result.stdout.includes("windmill-ts:"), false);
    assert.equal(result.stdout.includes("cache directory"), false);
  });
});

test("offline generation with complete inputs succeeds without a workspace", async () => {
  await withCwd(async (cwd) => {
    const result = runCli(["--from-folder", FIXTURE, "--offline", "-"], { cwd });
    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /export const runScript/);
  });
});

test("--from-folder conflicts with --workspace", async () => {
  await withCwd(async (cwd) => {
    const result = runCli(["--from-folder", FIXTURE, "--workspace", "x", "-"], {
      cwd,
    });
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /cannot be used together/);
  });
});

test("local-only options in remote mode are usage errors", async () => {
  await withCwd(async (cwd) => {
    for (const args of [
      ["--offline", "-"],
      ["--cache-dir", "/tmp/x", "-"],
      ["--resource-types-file", "/tmp/x.json", "-"],
    ]) {
      const result = runCli(args, { cwd });
      assert.notEqual(result.status, 0);
      assert.match(result.stderr, /only valid in local mode/);
    }
  });
});

test("no --refresh-hub-types option is advertised", async () => {
  const result = runCli(["generate", "--help"], {});
  assert.equal(result.status, 0, result.stderr);
  assert.equal(result.stdout.includes("--refresh-hub-types"), false);
  assert.match(result.stdout, /--from-folder/);
  assert.match(result.stdout, /--offline/);
});

test("config-only source.folder selects local mode and resolves relative to the config", async () => {
  await withCwd(async (cwd) => {
    await cp(FIXTURE, join(cwd, "ws"), { recursive: true });
    await writeFile(
      join(cwd, "windmill-ts.yaml"),
      "source:\n  folder: ./ws\n",
    );
    const result = runCli(["-"], { cwd });
    assert.equal(result.status, 0, result.stderr);
    assert.match(result.stdout, /^\/\/ This file is auto-generated/);
  });
});

test("explicit --workspace selects remote mode even when config has source.folder", async () => {
  await withCwd(async (cwd) => {
    await writeFile(
      join(cwd, "windmill-ts.yaml"),
      `source:\n  folder: ${FIXTURE}\n`,
    );
    // A nonexistent workspace makes the remote path fail at the store lookup,
    // proving remote mode was selected rather than generating from the folder.
    const result = runCli(["--workspace", "definitely-not-a-workspace", "-"], {
      cwd,
    });
    assert.notEqual(result.status, 0);
    // Depending on whether a Windmill CLI store exists, the remote path fails
    // either reading remotes.ndjson or with the "not found" lookup error; both
    // prove remote mode (not folder generation) was selected.
    assert.match(
      result.stderr,
      /remotes\.ndjson|not found in Windmill CLI config/,
    );
    assert.equal(result.stdout.includes("auto-generated"), false);
  });
});

test("a malformed resource never leaks its source into CLI stderr (B1)", async () => {
  await withCwd(async (cwd) => {
    const folder = join(cwd, "ws");
    const secretFragment = "SUPER_SEC";
    const secret = "SUPER_SECRET_DO_NOT_LOG_9f3a2b";
    // A separate source folder holding one malformed resource file.
    await mkdir(folder, { recursive: true });
    await writeFile(
      join(folder, "bad.resource.yaml"),
      `resource_type: redis\nvalue:\n  password: [${secret}\n`,
    );
    const result = runCli(["--from-folder", folder, "--offline", "-"], { cwd });
    assert.notEqual(result.status, 0);
    assert.match(result.stderr, /bad\.resource\.yaml/);
    assert.equal(result.stderr.includes(secretFragment), false);
    assert.equal(result.stdout.includes(secretFragment), false);
  });
});
