import dedent from "dedent";
import { getContext } from "./context.js";

const preamble = dedent`
  // This file is auto-generated by windmill-ts, do not modify it manually
  import { z } from 'zod';
  import * as wmill from 'windmill-client';

  const lazyObject = <T,>(fn: () => T) => {
    let instance: T | null = null;
    return new Proxy({}, {
      get(_target, prop) {
        if (instance == null) {
          instance = fn();
        }

        let value = (instance as never)[prop];
        if (value instanceof Function) {
          value = value.bind(instance);
        }

        return value;
      }
    }) as T;
  }
`;

export const writePreamble = async () => {
  const { write } = getContext()!;

  await write(preamble);
};
